categories:
  - title: ":boom: Breaking Changes"
    label: "breaking"
  - title: ":rocket: Features"
    label: "enhancement"
  - title: ":fire: Removals and Deprecations"
    label: "removal"
  - title: ":beetle: Fixes"
    label: "bug"
  - title: ":racehorse: Performance"
    label: "performance"
  - title: ":rotating_light: Testing"
    label: "testing"
  - title: ":construction_worker: Continuous Integration"
    label: "ci"
  - title: ":books: Documentation"
    label: "documentation"
  - title: ":hammer: Refactoring"
    label: "refactoring"
  - title: ":lipstick: Style"
    label: "style"
  - title: ":package: Dependencies"
    labels:
      - "dependencies"
      - "build"

autolabeler:
  - label: 'documentation'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feat\/.+/'
    body:
      - '/JIRA-[0-9]{1,4}/'
  - label: 'refactoring'
    branch:
      - '/refactor\/.+/'
    title:
      - '/^refactor/i'
  - label: 'testing'
    branch:
      - '/test\/.+/'
  - label: 'breaking'
    title:
      - '/breaking change/i'
  - label: 'ci'
    files:
      - '.github/*'

template: |
  ## Changes

  $CHANGES
