name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)
# Pipeline triggers on any branch and tag
trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

resources:
  repositories:
    - repository: templates
      type:       github
      name:       statisticsnorway/azure-pipelines-templates
      ref:        refs/tags/1.1.30
      endpoint:   statisticsnorway

# Pipeline will be run on this base image
pool:
  vmImage: 'ubuntu-latest'

# Variables global to this pipeline
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
variables:
  # Variables defined in Pipelines->Library->Variable Groups in your project in
  # Azure Pipelines
  - group: Hemmeligheter
  # Variables defined here
  - name:  MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository
  - name: MAVEN_OPTS
    value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'


# Job which will run mvn build, mvn install and Sonar Analysis (if branch is master)
jobs:

  - template: java/library-complete-build.yml@templates
    parameters:
      artifactName: dapla-dlp-pseudo-func
      mavenContainer: maven:3.8-openjdk-17
      checkStyleRunAnalysis: true
      pmdRunAnalysis: true
      sonarQubeRunAnalysis: true
      sonarCloud: bipSonarCloud-Dapla
